name: Reusable CD

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
    - shell: bash
      run: |
        echo "✅ Deployment in progress for environment: 'inputs: ${{ inputs.environment }}' and 'github: ${{ github.environment }}'."
