name: Deployment
on: 
  push:
    branches:
      - 'release**'
  workflow_dispatch:

jobs:
  dev-deploy:
    uses: ./.github/workflows/cd-reusable.yml
    with:
      environment: dev
  hom-deploy:
    needs: dev-deploy
    uses: ./.github/workflows/cd-reusable.yml
    with:
      environment: hom
  prod-deploy:
    needs: hom-deploy
    uses: ./.github/workflows/cd-reusable.yml
    with:
      environment: prod
