name: Deployment
on: 
  push:
    branches:
      - 'release**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 10

      - id: reusable-cd
        uses: './.github/actions/cd'
        with:
          environment: dev
