name: Check PR Branch

on:
  pull_request:
    branches:
      - main
jobs:
  check-pr-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR branch starts with "fail"
        run: |
          echo "PR source branch: ${{ github.head_ref }}"
          BRANCH_NAME="${{ github.head_ref }}"

          if [[ "$BRANCH_NAME" == fail* ]]; then
            echo "Branch starts with 'fail'. Exiting with code 1."
            exit 1
          else
            echo "Branch does not start with 'fail'. Exiting with code 0."
            exit 0
          fi
